language: node_js
install:
    - sudo apt-get update
    - sudo apt-get install libssl1.0.0-dbg
    - npm install -g istanbul
    - npm install -g codeclimate-test-reporter
    - npm install -g coveralls
    - npm install
    - npm install codecov.io
node_js:
    - "node"
    - "iojs"
script:
    - istanbul cover node_modules/mocha/bin/_mocha test/openssl.js
after_script:
    - codeclimate < coverage/lcov.info
    - coveralls < coverage/lcov.info
    - node_modules/codecov.io/bin/codecov.io.js < coverage/coverage.json
