language: node_js
install:
    - npm install -g istanbul
    - npm install -g codeclimate-test-reporter
    - npm install
node_js:
    - "node"
    - "iojs"
script:
    - istanbul cover node_modules/mocha/bin/_mocha
after_script:
    - codeclimate < coverage/lcov.info
